# [공통 설정] - 모든 환경에서 적용됨
app:
  upload:
    root-dir: /upload

server:
  tomcat:
    max-http-form-post-size: 2MB
    max-swallow-size: 2MB

spring:
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB
      resolve-lazily: true

  profiles:
    active: local

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  thymeleaf:
    cache: false

security:
  jwt:
    secret: ${SECURITY_JWT_SECRET:this-is-a-very-long-secret-key-at-least-32-bytes!!}
    expiration: 86400000

---
# [서버 환경] - prod 프로필이 활성화될 때 적용됨
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: pbuser
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false

  thymeleaf:
    cache: true

# 로그 파일 생성 및 관리 설정 추가
logging:
  file:
    name: /home/ubuntu/logs/spring.log  # CloudWatch 에이전트가 읽어갈 경로
  logback:
    rollingpolicy:
      max-history: 7                  # 7일치 로그만 보관하여 디스크 절약
      max-file-size: 10MB             # 파일당 10MB로 제한
  level:
    root: info
    org.hibernate.SQL: info